connection awsiot

address your-endpoint-ats.iot.your-region.amazonaws.com:8883

topic sensors/humidity out 1
topic sensors/light out 1
topic sensors/temperature out 1

bridge_protocol_version mqttv311
bridge_insecure false

cleansession true
clientid bridge
start_type automatic
notifications false
log_type all


#Path to the rootCA
bridge_cafile /etc/mosquitto/certs/AmazonRootCA1.pem

# Path to the PEM encoded client certificate
bridge_certfile /etc/mosquitto/certs/bridge.cert.pem

# Path to the PEM encoded client private key
bridge_keyfile /etc/mosquitto/certs/bridge.private.key

#END of bridge.conf